### ISSUE TITLE
Clarity of the official doc

### ISSUE THREAD

**Issue by wilsonwg** [SachinAgarwal1337/google-places-api#55]
Hi, thx for making the convenient package.
I just want thing to be added to the official doc.
To use with Laravel 5.5 above with the auto discovery feature, this line needs to be added for the usage:

**use GooglePlaces;**

I found this after a period of Google search:
https://laracasts.com/discuss/channels/general-discussion/a-new-open-source-package-for-google-places-api

And also add 

GOOGLE_PLACES_API_KEY=YOUR_API_KEY 

to .env

I don't see these in the documentation. And I think they should be part of the official doc.

**Comment by SachinAgarwal1337** [comment]
@wilsonwg 
The Reason **use GooglePlaces** is not part of the documentation is because:
1. It is optional, you can use the mail class as well
2. It can be seen in the manual setup
3. Also it is obvious when using Facade with laravel that it has to be included.

and about env I mentioned it here https://github.com/SachinAgarwal1337/google-places-api#step-2

Hope this gives clarity :)
